### ISSUE TITLE
Input persistency

### ISSUE THREAD

**Issue by BeNeNuTs** [BeNeNuTs/Kakuto#101]
Input persistency algo à changer pour pouvoir rentrer des combos plus longue sans avoir à augmenter ce param. Sinon on est obligé de rallonger l'input persistency pour tout le monde uniquement dans le but d'avoir le temps de faire toute la chaine d'input d'une attaque (comme les supers). Peut être reset le timer de chaque input à chaque fois qu'un nouvel input est envoyé ?

**Comment by Nikuichi** [comment]
Une fois fixé, check :
- EX moves
- 2 QCF moves 
- Input buffer
