### ISSUE TITLE
Implement parry system

### ISSUE THREAD

**Issue by Nikuichi** [BeNeNuTs/Kakuto#104]
Parry is an attack dealing no damage. 
It branches into two behaviors depending on the context :

- P1 is hit during parry animation.
P1 performs counterattack animation, receives no DMG, hitstun or blockstun.
![parry_success](https://user-images.githubusercontent.com/12612621/70951490-d83dc780-2063-11ea-8a0f-d2ba90a47ed3.gif)

- P1 is not hit during parry animation.
P1 performs parry whiff animation and goes back to idle.
![parry_whiff](https://user-images.githubusercontent.com/12612621/70951524-f4416900-2063-11ea-8020-d5df0a926ab1.gif)

REF
https://youtu.be/NdrGKa2_rOU?t=17

**Comment by BeNeNuTs** [comment]
J'ai quelques questions sur le parry parce que je vois pas bien sur la vidéo.
L'animation est plus ou moins découpée en 3 parties : la startup, la whiff, et la counter. 
1. On joue la startup, est-ce que dès qu'on détecte un hit, un cut l'anim de startup et on joue direct la counter ? (j'imagine que oui)
2. Est-ce que si on a pas détecté de hit et qu'on commence à jouer l'anim de whiff, si on détecte un hit on peut quand même jouer la counter ? Ou bien c'est trop tard et on prend le dégât en hit ?
3. Que se passe-t-il pour le joueur qui se fait contrer ? Est-ce que ça stop son attaque en cours ? Ou genre ça désactive ces hitboxes ? Parce que si jamais on fait pas ça, ça veut dire qu'on va jouer l'anim de counter du parry (je sais pas si les hurtboxes sont désactivées ou pas à ce moment là), mais vu que les hitboxes de l'adversaire sont potentiellement encore actives et qu'on a pas stop l'attaque, dès qu'on aura terminé le parry, on risque de prendre le hit.

**Comment by Nikuichi** [comment]
1. Oui.
2. Trop tard.
3. Le mieux serait de faire en fonction du max count de l'attaque en question. Tu dois parry autant de hit que l'attaque peut en infliger. Si tu réussis à parry le seul/dernier hit de l'attaque, elle ne peut plus te faire de dégâts. 
Le parry en lui-même c'est comme si tu 'encaissais un hit sans prendre de dégâts ni de hitstun.

https://youtu.be/0RnEsjfKSH4?t=27

**Comment by BeNeNuTs** [comment]
Le trigger de Malik qui rend le prochain non super projectile imblocable, peut quand même être parry
- Nikuichi, le 04/01/2020 à 22h44
