### ISSUE TITLE
Implement proximity guard collision boxes

### ISSUE THREAD

**Issue by Nikuichi** [BeNeNuTs/Kakuto#105]

**Comment by BeNeNuTs** [comment]
@Nikuichi Je pense qu'il me faudrait un commentaire détaillé de ce qu'il se passe. Comment ça se déclenche, pendant combien de temps, qu'est ce qu'il se passe si on prend le hit pendant le proximity guard, est-ce que si je relâche l'input back, je continue de proximity guard pendant un moment, etc etc

**Comment by Nikuichi** [comment]
https://docs.google.com/document/d/1H10QftBdKZLwO_zEkFUJzifObqk8quHQa12sZsMTH0U/edit#heading=h.trdw1wvx5rb

HF

**Comment by BeNeNuTs** [comment]
Merki !
Question : c'est P1 qui crée la proximity box pendant l'attaque ? Ce serait pas plus simple d'avoir une proximity box sur le P2 et on détecte l'entrée / sortie des hitbox de P1 dedans ?
Y'a du proximity guard en crouch ?

**Comment by Nikuichi** [comment]
Euh tu mets les box sur qui tu veux tant que le résultat est le meme.

Ya proxy guard en crouch, meme si tu ne peux pas reculer.

**Comment by BeNeNuTs** [comment]
Est-ce que la proximity guard se déclenche si on est pas dans la bonne stance par rapport à lattack ? Exemple, je fais back en stand mais je reçois une attack low. Ou bien c'est les mêmes conditions qu'un block normal ? Sachant que ça va être relou car le CanBlock return false quand lattack qui arrive est imblocable... alors qu'on voudrait trigger la proximity quand même j'imagine ^^

**Comment by Nikuichi** [comment]
J'ai une mauvaise nouvelle à t'annoncer.

Oui.

**Comment by BeNeNuTs** [comment]
Ouais mais non en fait c'est une bonne nouvelle finalement si tu me dis que le proximity guard se déclenche qu'à partir du moment où t'es dans une pose de guard (en faisant back) sans prendre en compte l'attaque. J'ai déjà fait une méthode qui permet de savoir si tu fais back etc sans tenir compte de l'attaque (imblocable/stance etc)

**Comment by BeNeNuTs** [comment]
Ne pas oublier InitHitBoxes (ajouter layer ProximityBox)
