### ISSUE TITLE
Implement stun gauge

### ISSUE THREAD

**Issue by Nikuichi** [BeNeNuTs/Kakuto#107]
- Chaque coup en hit inflige une quantité différente de stun à l'adversaire.
- Tant que l'adversaire est en hitstun ou blockstun et pendant X secondes après, la jauge de stun ne peut pas diminuer.
- Après cette durée, la jauge diminue à une fréquence donnée pour revenir à zéro.
- Le dernier coup à remplir la jauge de l'adversaire le fait forcément tomber au sol, après quoi il se relève et joue l'anim de stun pendant X secondes, puis l'anim de récupération, puis l'idle.

**Comment by BeNeNuTs** [comment]
![96F36883](https://user-images.githubusercontent.com/2429048/71092788-2fe54b80-21a8-11ea-824a-976c491aebd4.PNG)
