### ISSUE TITLE
Players can dash through each other

### ISSUE THREAD

**Issue by Nikuichi** [BeNeNuTs/Kakuto#109]
Checker les pushbox.

![dash_through](https://user-images.githubusercontent.com/12612621/71299858-46e69200-2390-11ea-9c6a-ecb5e6ee7459.gif)

**Comment by BeNeNuTs** [comment]
@Nikuichi : Je suis pas sûr que ça vient des pushbox. À mon avis c'est le root motion qui bouge la position des persos. À force ça fini par passer au travers

**Comment by Jesaypa** [comment]
Issue still occurs - _12/01/19_

**Comment by BeNeNuTs** [comment]
Idem #133. J'ai fixé l'issue en code, comme expliqué à RV, il faut maintenant s'assurer que les pushbox des 2 players ne passent pas l'une derrière l'autre à cause du fait qu'on les déplace dans l'animation. Normalement mon fix fait en sorte qu'on ne déplace plus l'entité si "quelque chose bloque" mais ne préviens pas le fait qu'une pushbox puisse être placé de l'autre côté d'un joueur. Une fois que la physique est calculé, on aura automatiquement un swap des joueurs ^^
