### ISSUE TITLE
Players can still start a normal while being hit

### ISSUE THREAD

**Issue by Nikuichi** [BeNeNuTs/Kakuto#110]
Le joueur de droite lance un s.HK alors qu'il est touché par le j.HK du joueur de gauche.

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/12612621/71299949-1a7f4580-2391-11ea-8964-3a35a7d98e27.gif)

**Comment by Jesaypa** [comment]
CNR - _11/01/19_

**Comment by Jesaypa** [comment]
Issue has been reproduced - 19/04

>Issue seems easier to repro by starting s.HK just before being hit by the j.HK.

[KAKUTO_110_P2.txt](https://github.com/BeNeNuTs/Kakuto/files/4499492/KAKUTO_110_P2.txt)
[KAKUTO_110_P1.txt](https://github.com/BeNeNuTs/Kakuto/files/4499493/KAKUTO_110_P1.txt)

**Comment by BeNeNuTs** [comment]
Partially fixed by https://github.com/BeNeNuTs/Kakuto/commit/d268a0d8d3cacb90cbb61d6d4c4e6652ef699df2

**Comment by BeNeNuTs** [comment]
Should be fixed with 80f8551
