### ISSUE TITLE
Malik can move while standing up

### ISSUE THREAD

**Issue by Nikuichi** [BeNeNuTs/Kakuto#111]
![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/12612621/71299956-2bc85200-2391-11ea-8d67-6492c06ceea6.gif)

**Comment by BeNeNuTs** [comment]
Je pense que c'est la même issue que celui la : https://github.com/BeNeNuTs/Kakuto/issues/56

**Comment by Nikuichi** [comment]
Aussi identique à #120
