### ISSUE TITLE
Players might not be pushed back when receiving a hit

### ISSUE THREAD

**Issue by Nikuichi** [BeNeNuTs/Kakuto#112]
![ezgif com-video-to-gif (3)](https://user-images.githubusercontent.com/12612621/71299989-6a5e0c80-2391-11ea-825c-dd847af8a3c7.gif)

**Comment by Jesaypa** [comment]
CNR - _11/01/2019_

**Comment by Jesaypa** [comment]
**_CNR 19/04_**
