### ISSUE TITLE
Players might not perform the backflip animation when hit in the air

### ISSUE THREAD

**Issue by Nikuichi** [BeNeNuTs/Kakuto#113]
![ezgif com-video-to-gif (4)](https://user-images.githubusercontent.com/12612621/71300007-88c40800-2391-11ea-8858-ce766583d7ea.gif)

![ezgif com-video-to-gif (12)](https://user-images.githubusercontent.com/12612621/71300213-118f7380-2393-11ea-98d8-0e4f91b9fdd1.gif)

**Comment by BeNeNuTs** [comment]
@Nikuichi Je pense qu'on trigger pas le root motion à la première trame d'animation. Du coup avec la gravité, sa groundBox touche le sol et cancel l'anim pour repasser en stand idle

**Comment by Jesaypa** [comment]
@Nikuichi need 1v1 repro.

**Comment by Nikuichi** [comment]
@Jesaypa Ca en devrait plus repro, on a retiré le rootmotion sur le hitair. (je crois)

**Comment by BeNeNuTs** [comment]
J'ai fixé des trucs récemment sur la gravité + rootmotion :) FYI

**Comment by BeNeNuTs** [comment]
On peut close celui-ci nan ?

**Comment by Nikuichi** [comment]
Je l'ai mis en need repro pour repasser dessus et le closer si nécessaire.

**Comment by Jesaypa** [comment]
YO WADDUP

![KAK_113_repro](https://user-images.githubusercontent.com/11633563/94614745-f436f080-02a6-11eb-84a1-1be199db0853.gif)

[Player2Chronicle.txt](https://github.com/BeNeNuTs/Kakuto/files/5301815/Player2Chronicle.txt)
[Player1Chronicle.txt](https://github.com/BeNeNuTs/Kakuto/files/5301816/Player1Chronicle.txt)

J'arrive à repro sur une redescente de jump du perso, mais ça reste assez précis. Je pense que ça ne se produit que sur les hit qui ont un knockdown, avec les autres types de coups on tombe sur l'animation de hit aérien sans trop de problème:
![KAK_113_exemple](https://user-images.githubusercontent.com/11633563/94615261-c2725980-02a7-11eb-8ce2-4c5c9fa7cf73.gif)

**Comment by Nikuichi** [comment]
Jacky avait réussi à repro, tu peux checker ?

**Comment by BeNeNuTs** [comment]
21517  - [Health]    On hit by : standHK, damage : 10, result : Hit, hitNotif : None
21517  - [Health]    On damage taken : 10, current HP : 1
21517  - [Stun]      Start stun | Type : Hit, Duration anim driven : True
21517  - [Movement]  Movement has been blocked, reason : Stun
21517  - [Movement]  On movement stopped
21517  - [Attack]    On stun begin | Attack is blocked
21517  - [Movement]  On Landing
21517  - [Movement]  On player stance changed | Old stance : Jump    New stance : Stand  
21517  - [Movement]  On player jump phase changed | Old phase : Air      New phase : Landing

**Comment by BeNeNuTs** [comment]
Ce qu'il se passe c'est qu'on reçoit le hit à la même trame qu'on détecte le landing. En fait c'est justement parce que dans cette même trame on détecte le landing juste après avoir reçu le hit que ça pose problème.

En gros : 
- On reçoit le hit => ça play hit_air
- Dans la même trame, on reçoit landing qui set le "is jumping" à false.
- Et vu que le graph ressemble à ça : 
![image](https://user-images.githubusercontent.com/2429048/96375298-787ae600-1178-11eb-9864-c1276661a18a.png)
HitJump = hit_air
Et lorsque IsJumping passe à false, on peut faire une transition vers JumpLanding n'importe quand (donc ici, dès la première trame)
Pour fixer, on pourrait dire que la transition de HitJump vers JumpLanding est check qu'une fois que HitJump est terminé (ce qui est le cas pour la transition HitJump -> JumpIdle.
Qu'est ce que vous en pensez ? 
@Nikuichi @Jesaypa
