### ISSUE TITLE
Throw animations might be asynchronized between players

### ISSUE THREAD

**Issue by Nikuichi** [BeNeNuTs/Kakuto#114]
![ezgif com-video-to-gif (5)](https://user-images.githubusercontent.com/12612621/71300030-bf9a1e00-2391-11ea-9de7-55ba5707f687.gif)

![ezgif com-video-to-gif (11)](https://user-images.githubusercontent.com/12612621/71300200-fae91c80-2392-11ea-94bd-fddbadb1f357.gif)

**Comment by Jesaypa** [comment]
@Nikuichi need repro en 1v1.

**Comment by Jesaypa** [comment]
Issue reproduced - _11/01/19_
