### ISSUE TITLE
Players might not turn around when jumped over

### ISSUE THREAD

**Issue by Nikuichi** [BeNeNuTs/Kakuto#115]
![ezgif com-video-to-gif (6)](https://user-images.githubusercontent.com/12612621/71300064-0425b980-2392-11ea-97bb-4fa480874304.gif)

**Comment by Jesaypa** [comment]
Hard to repro. Might still occurs while:
-Chaining forward-throw on the corner
-Jumping above the opponent just before the standup animation
Only 1 occurence - _08/01/19_

UPDATE:
Manage to repro by:
-Pushing the opponent to the corner
-Dashing against him before reaching the corner
-Feedback to know if the position is right is to try a throw > If it's fail, then the position is good (_new bug will be open for this)_
-Jump over the opponent
[Video coming soon]

**Comment by Jesaypa** [comment]
![KAKUTO_115-g](https://user-images.githubusercontent.com/11633563/72208374-2e0a6180-34a2-11ea-82a2-43700cac7c8f.gif)

**Comment by Jesaypa** [comment]
On peut également reproduire l'issue très facilement en faisant un j.HK en crossup.

**Comment by Jesaypa** [comment]
**_CNR 18/04_**
