### ISSUE TITLE
Players can cancel a normal with itself

### ISSUE THREAD

**Issue by Nikuichi** [BeNeNuTs/Kakuto#116]
![ezgif com-video-to-gif (7)](https://user-images.githubusercontent.com/12612621/71300070-1f90c480-2392-11ea-8bc7-79467aacfdbb.gif)

P1 était en train de spammer c.HP

**Comment by Jesaypa** [comment]
CNR on solo. Might be due to the hit received by P1 just before - 08/01/19

**Comment by DocUnco** [comment]
It's possible to do Normal > Special > Spam Normal.

Current combo is : LP > HadoGround > Spam LP.

It works with after others special move if they have been cancel.

![SpecialCancel](https://user-images.githubusercontent.com/3359512/74616910-c2638600-512a-11ea-8bb0-c95ef7423b8f.gif)

**Comment by BeNeNuTs** [comment]
Ca devrait être fixed avec la CL que j'ai en local :) j'ai pas osé submit avant de partir en vacances pour pas faire un showstopper mais ça devrait le faire ;)
