### ISSUE TITLE
Players might get stuck in blockstun loop anim

### ISSUE THREAD

**Issue by Nikuichi** [BeNeNuTs/Kakuto#117]
![ezgif com-video-to-gif (8)](https://user-images.githubusercontent.com/12612621/71300100-641c6000-2392-11ea-9259-8453d398c86a.gif)

Repro uniquement avec cHK pour l'instant.

**Comment by Jesaypa** [comment]
Issue still occurs  - 08/01/19

**Comment by Jesaypa** [comment]
Issue has been repro **_19/04_**

>Issue only occurs while blocking a sweep on crouch position
[KAKUTO_117_P2.txt](https://github.com/BeNeNuTs/Kakuto/files/4499539/KAKUTO_117_P2.txt)
[KAKUTO_117_P1.txt](https://github.com/BeNeNuTs/Kakuto/files/4499540/KAKUTO_117_P1.txt)

**Comment by BeNeNuTs** [comment]
Should be fixed by 46ac808
