### ISSUE TITLE
Malik walking speed should not be analogic

### ISSUE THREAD

**Issue by Nikuichi** [BeNeNuTs/Kakuto#118]
![ezgif com-video-to-gif (9)](https://user-images.githubusercontent.com/12612621/71300124-89a96980-2392-11ea-985b-a946c3e3b719.gif)

Obtenu en poussant très légèrement le stick.

**Comment by BeNeNuTs** [comment]
@Nikuichi  J'étais sûr de l'avoir fixé celui ci. Peut être plus présent dans la version

**Comment by BeNeNuTs** [comment]
Déjà fixé, mais je vais refaire une petite passe parce que jsuis pas très content de ce que ça donne ^^ En gros l'input s'affiche mais le perso n'avance pas tant qu'on dépasse pas la moitié du stick.

**Comment by BeNeNuTs** [comment]
Tu me diras si ça te va ;)
