### ISSUE TITLE
Getting hit by a sweep during jump startup sends Malik flying upward

### ISSUE THREAD

**Issue by Nikuichi** [BeNeNuTs/Kakuto#119]
![ezgif com-video-to-gif (10)](https://user-images.githubusercontent.com/12612621/71300180-e016a800-2392-11ea-8864-4d56fe250650.gif)

**Comment by BeNeNuTs** [comment]
J'ai limite envie de le laisser celui là il est rigolo : D

**Comment by Nikuichi** [comment]
Taisez-vous.

**Comment by Jesaypa** [comment]
Issue has been reproduced - _08/01/19_
