### ISSUE TITLE
Crouch attacks can be performed midair

### ISSUE THREAD

**Issue by Nikuichi** [BeNeNuTs/Kakuto#121]
![jump_crouch](https://user-images.githubusercontent.com/12612621/71300267-4bf91080-2393-11ea-84d8-1c75cf82badd.gif)

Déclencher un saut et faire un coup baissé aussi vite que possible après.

**Comment by Jesaypa** [comment]
Issue still occurs  - 08/01/19

**Comment by BeNeNuTs** [comment]
Je vois d'où ça vient, c'est depuis le dev où on applique le jump impulse uniquement à la fin du takeOff. Faut que je clean un peu cette partie car la logique peut être décorélée du visuel (l’animation)

**Comment by Jesaypa** [comment]
No repro after further testing on version from _24/01/2020_
