### ISSUE TITLE
Add a super gauge cost to attacks

### ISSUE THREAD

**Issue by Nikuichi** [BeNeNuTs/Kakuto#122]
Un champ pour déterminer le coût en jauge de super de n'importe quel coût spécial ou super. 
Quand le coup en question est déclenché, son coût est déduit de la jauge.
Si le montant demandé n'est pas disponible, le coup ne se déclenche pas.

**Comment by BeNeNuTs** [comment]
Déjà fait dans les conditions de déclenchements de l'attaque

**Comment by BeNeNuTs** [comment]
![image](https://user-images.githubusercontent.com/2429048/71476368-fe423500-27e4-11ea-920c-148b466c7c89.png)
