### ISSUE TITLE
Player may not perform hit animation when receiving a hit after a j.HK

### ISSUE THREAD

**Issue by Jesaypa** [BeNeNuTs/Kakuto#125]
Players faisant un j.HK tout en recevant un s.HK peut ne pas jouer d'animation de hit.

![KAKUTO_125_g](https://user-images.githubusercontent.com/11633563/72208619-30ba8600-34a5-11ea-8715-057e15e06c6b.gif)

**Comment by Nikuichi** [comment]
Plus précisément j'ai l'impression que c'est quand tu reçois un hit pendant le jump landing.

**Comment by BeNeNuTs** [comment]
Je pense que le hit est joué quasiment au moment où le player touche le sol donc il repasse en idle direct

**Comment by BeNeNuTs** [comment]
CNR. surement après le fix du root motion
