### ISSUE TITLE
Allow triggers and bumpers as attack inputs

### ISSUE THREAD

**Issue by Nikuichi** [BeNeNuTs/Kakuto#126]
Il faudrait qu'on puisse utiliser 
sur Xbox : RB / LB / RT / LT
sur PS4 : R1 / R2 / L1 / L2

**Comment by BeNeNuTs** [comment]
![LogitechInputMapping](https://user-images.githubusercontent.com/2429048/72259633-3d5bed00-3611-11ea-82df-096bfe69b627.PNG)
