### ISSUE TITLE
Hadoblast may not push back or hit the opponent if performed too close from him.

### ISSUE THREAD

**Issue by Jesaypa** [BeNeNuTs/Kakuto#128]
![KAKUTO_128](https://user-images.githubusercontent.com/11633563/72223097-d0424c00-356b-11ea-8925-c28ef6f0dc2b.gif)

**Comment by BeNeNuTs** [comment]
@Nikuichi : Je pense qu'il faut agrandir la hitbox ou les pushbox pour éviter qu'ils se passent au travers
