### ISSUE TITLE
Malik's model are overlaping while staying idle too close from each other.

### ISSUE THREAD

**Issue by Jesaypa** [BeNeNuTs/Kakuto#129]
![KAKUTO_129_g](https://user-images.githubusercontent.com/11633563/72682979-85788500-3ad3-11ea-9251-c77bd4ce8f18.gif)

**Comment by BeNeNuTs** [comment]
@Nikuichi @Jesaypa  On augmente la pushbox ici ou bien je fais en sorte qu'il y en ait toujours un devant l'autre ? Ou bien plus complexe, P1 est toujours devant P2 mais dès que y'en a un qui lance une attaque il passe devant l'autre ?

**Comment by Nikuichi** [comment]
@BeNeNuTs On se casse pas la tête. P1 est toujours devant P2. On essaie avec ça mais ça devrait suffire.

**Comment by BeNeNuTs** [comment]
@Nikuichi Je suis pas sûr que ça va suffire car pendant un grab par exemple, P2 aura la main qui passe derrière P1. Bref je vais essayer et on verra :)
