### ISSUE TITLE
Front jumping while close from the opponent do not allow to pass behind him

### ISSUE THREAD

**Issue by Jesaypa** [BeNeNuTs/Kakuto#130]
![KAKUTO_130_g](https://user-images.githubusercontent.com/11633563/72682997-bbb60480-3ad3-11ea-90af-b995d84dd5fb.gif)

If the player is really close from the opponent, front jump will touch him or "bounce" on his head but will not be able to go behind.
If the player just back a little, going behind will be possible which is really weird on gameplay purpose.

**Comment by Nikuichi** [comment]
@Jesaypa Il faut qu'on check si c'est toujours aussi grave.

**Comment by Jesaypa** [comment]
C'est bien mieux qu'au moment du report. Plus vraiment de difficulté à passer par dessus l'adversaire.
Je close.
