### ISSUE TITLE
After dashing through the opponent while on the corner, player keep the dash movement ongoing.

### ISSUE THREAD

**Issue by Jesaypa** [BeNeNuTs/Kakuto#133]
![KAKUTO_133_g](https://user-images.githubusercontent.com/11633563/74192846-9e013880-4c56-11ea-87fb-4b93f2fbe406.gif)

If the player keep dashing forward when reaching the corner, then he will go though the opponent by keeping the dash movement ongoing. 
**Look at the registered inputs for clearer informations.**

**Comment by Nikuichi** [comment]
Probablement pareil que #109

**Comment by BeNeNuTs** [comment]
> Probablement pareil que #109

Pas vraiment pareil mais disons que ce sera fixé quand l'issue #109 le sera :) Vu qu'on flip le perso dès qu'il passe de l'autre côté automatiquement le dash se termine dans l'autre sens

**Comment by BeNeNuTs** [comment]
J'ai fixé l'issue en code, comme expliqué à RV, il faut maintenant s'assurer que les pushbox des 2 players ne passent pas l'une derrière l'autre à cause du fait qu'on les déplace dans l'animation. Normalement mon fix fait en sorte qu'on ne déplace plus l'entité si "quelque chose bloque" mais ne préviens pas le fait qu'une pushbox puisse être placé de l'autre côté d'un joueur. Une fois que la physique est calculé, on aura automatiquement un swap des joueurs ^^
