### ISSUE TITLE
Pushing the opponent while dashing is greatly reduced.

### ISSUE THREAD

**Issue by Jesaypa** [BeNeNuTs/Kakuto#135]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/11633563/76707988-ce277580-66f3-11ea-9900-88bbaa4642be.gif)

**Comment by Nikuichi** [comment]
Sync avec David pour voir ce qu'on avait dit à ce sujet.

**Comment by BeNeNuTs** [comment]
Y'a peut être une façon de fix ça, je vient de faire un test mais en augmentant la masse du Rigidbody de celui qui lance le dash (et en augmentant la force du dash pour qu'il parcourt toujours la même distance qu'avant) il pousse beaucoup plus l'adversaire (normal car il est beaucoup plus lourd que lui à présent ^^). à voir si ça vous convient.
