### ISSUE TITLE
After a f.throw on the corner, player can still manage to pass through the opponent

### ISSUE THREAD

**Issue by Jesaypa** [BeNeNuTs/Kakuto#136]
![KAKUTO_136_g2](https://user-images.githubusercontent.com/11633563/76708129-cc11e680-66f4-11ea-9a1a-09ddf093bc2a.gif)

![KAKUTO_136_g1](https://user-images.githubusercontent.com/11633563/76708130-ccaa7d00-66f4-11ea-951a-1cecfd4e1be7.gif)

**Comment by Jesaypa** [comment]
![KAKUTO_136_g1](https://user-images.githubusercontent.com/11633563/76708115-bac8da00-66f4-11ea-8e58-f4c0f68869bb.gif)

![KAKUTO_136_g2](https://user-images.githubusercontent.com/11633563/76708117-be5c6100-66f4-11ea-93dc-ab4f1c82a7fd.gif)

**Comment by BeNeNuTs** [comment]
C'est le même bug que #53 je pense. C'est le dash qui fait passer au travers de l'autre perso
