### ISSUE TITLE
"Effect" section on PlayerAttackConfig inspector might be blurry sometimes.

### ISSUE THREAD

**Issue by Jesaypa** [BeNeNuTs/Kakuto#137]
![KAKUTO_137_g](https://user-images.githubusercontent.com/11633563/78456954-393aeb00-76a7-11ea-99a7-2080f7e74094.gif)

![2020-04-04_19h00_08](https://user-images.githubusercontent.com/11633563/78456968-48ba3400-76a7-11ea-834f-6c4961b0f05a.png)

-Openning an attack list then having to scroll down to check the "Effect" section may display both of them really blurry. 
-It can also scroll up automatically the inspector or annoy the user to perform a selection on any other section.

**Workaround:**
-If the "Effect" section is directly displayed while openning an attack list, the bug will not occurs.

**Comment by BeNeNuTs** [comment]
Désolé je pense pas que je pourrai fix celui là. C'est pas moi qui ai codé ce behavior, c'est un bout de code que j'ai récup sur Internet pour cacher certains champs en fonction d'une checkbox (ça existe pas de base sur Unity).

**Comment by Jesaypa** [comment]
Partially fixed with recent CL. Engine issue anyway.
