### ISSUE TITLE
Hadoblast do not pushback on the last hit.

### ISSUE THREAD

**Issue by Jesaypa** [BeNeNuTs/Kakuto#138]
![KAKUTO_138_g](https://user-images.githubusercontent.com/11633563/79048480-9beb3400-7c1d-11ea-98df-813038bc2320.gif)

**Comment by BeNeNuTs** [comment]
Je viens de regarder et ça vient du fait que le "Delay between hits" ne permet pas à l'attaque d'atteindre son max hit count, du coup pas de pushback :/
![image](https://user-images.githubusercontent.com/2429048/79074841-e4265700-7cee-11ea-9e83-8488940e59a6.png)

**Comment by Jesaypa** [comment]
Issue _partially_ fixed with CL https://github.com/BeNeNuTs/Kakuto/commit/d1eb9a2913f2b7580d9df4b3597341b668a26b47.

**Comment by Jesaypa** [comment]
Second CL https://github.com/BeNeNuTs/Kakuto/commit/44dc6eb3e4514b6636b80b92ae0f5041bb176b0e to fixe the issue.
