### ISSUE TITLE
Sometimes player cannot move anymore after receiving a hit or performing a tech-throw.

### ISSUE THREAD

**Issue by Jesaypa** [BeNeNuTs/Kakuto#139]
![KAKUTO_139_g](https://user-images.githubusercontent.com/11633563/79692649-a5504e00-8266-11ea-8f1e-6f732b0ea2a0.gif)

Issue has been reproduce by performing a tech-throw or by simply receiving a hit without doing anything special.
The same error about "_an object cannot be destroyed_" seems to be triggered each time the issue is reproduce (sorry didn't get the error screen...).

LOGS:
[KAKUTO_139_P1.txt](https://github.com/BeNeNuTs/Kakuto/files/4499632/KAKUTO_139_P1.txt)
[KAKUTO_139_P1_2.txt](https://github.com/BeNeNuTs/Kakuto/files/4499633/KAKUTO_139_P1_2.txt)
[KAKUTO_139_P2.txt](https://github.com/BeNeNuTs/Kakuto/files/4499634/KAKUTO_139_P2.txt)
[KAKUTO_139_P2_2.txt](https://github.com/BeNeNuTs/Kakuto/files/4499635/KAKUTO_139_P2_2.txt)

**Comment by BeNeNuTs** [comment]
@Jesaypa : You can open the console, even after stopped the game, and select the error to have details, like this : 
![image](https://user-images.githubusercontent.com/2429048/79699080-5a95fc80-828d-11ea-847a-6f62f5fb4d26.png)
