### ISSUE TITLE
c.HK block pushback is not applied.

### ISSUE THREAD

**Issue by Jesaypa** [BeNeNuTs/Kakuto#141]
![KAKUTO_141_g](https://user-images.githubusercontent.com/11633563/80282779-a58f9400-8713-11ea-90c9-e68f1d656923.gif)

**LOGS:**
[KAKUTO_141_P1.txt](https://github.com/BeNeNuTs/Kakuto/files/4533186/KAKUTO_141_P1.txt)
[KAKUTO_141_P2.txt](https://github.com/BeNeNuTs/Kakuto/files/4533187/KAKUTO_141_P2.txt)

**Comment by BeNeNuTs** [comment]
@Jesaypa La capture est un peu flou du coup c'est chaud de voir le frame count mais grâce aux fichiers j'ai pu voir à quoi c'est dû. Le stun et le pushback sont mal géré quand une attaque est prise en block. Du coup faut que je regarde ça en faisant gaffe de pas tout casser x)
Merci pour les infos :)

**Comment by Jesaypa** [comment]
Désolé pour le record! je repasse en maximize on play à partir de maintenant.

Issue fixed. - _26/04_
