### ISSUE TITLE
Player quickly swap to Stand position after performing a Teleport while crouched.

### ISSUE THREAD

**Issue by Jesaypa** [BeNeNuTs/Kakuto#142]
![KAKUTO_142_g](https://user-images.githubusercontent.com/11633563/80306540-3f167e80-87c4-11ea-8ef2-47629ea742d1.gif)

**LOGS:**
[KAKUTO_142_P2.txt](https://github.com/BeNeNuTs/Kakuto/files/4535229/KAKUTO_142_P2.txt)
[KAKUTO_142_P1.txt](https://github.com/BeNeNuTs/Kakuto/files/4535230/KAKUTO_142_P1.txt)

**Comment by BeNeNuTs** [comment]
@Jesaypa @Nikuichi Je sais d'où ça vient mais par contre je sais pas trop comment fixer ça du coup j'en appelle à votre aide. Je vous explique :)
Quand tu lances l'attaque tu es en crouch, le teleport peut être lancé depuis une stance Stand ou Crouch donc jusque là ça va. Le problème c'est que l'attaque teleport est considérée comme une attaque Stand (Default stance), donc dès qu'on lance l'attaque ça change la stance du player automatiquement en stand. Juste pour rappel, ici ça peut pas arriver donc pas top pour l'exemple, mais on fait ça pour éviter de lancer une attaque qui visuellement est en stand alors que logiquement tu l'as lancé depuis la stance crouch, du coup si tu prends un hit ou quoi pendant cette attaque, tu vas jouer un hitCrouch alors que visuellement tu étais en stand, et aussi ça parait plus logique que ça blend vers du stand idle car l'attaque était en stand, bref...
Du coup, vu que le teleport a automatiquement changé ta stance de crouch à stand, bah à la fin ça blend vers StandIdle ^^ Et vu que tu gardes le crouch enfoncé, juste après tu repasses en crouch....
Voiloù voiloù ^^

**Comment by BeNeNuTs** [comment]
Vu avec Hervé, je vais rajouter une petite case à cocher pour savoir si on veut utiliser la default stance ou pas (ici vu que c'est un tp, on a pas besoin)
