### ISSUE TITLE
Player is stuck after being grabbed during jump startup

### ISSUE THREAD

**Issue by Nikuichi** [BeNeNuTs/Kakuto#144]
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/12612621/81843893-92235c00-954e-11ea-8d53-4557362f7eb3.gif)
[Player2Chronicle.txt](https://github.com/BeNeNuTs/Kakuto/files/4623553/Player2Chronicle.txt)
[Player1Chronicle.txt](https://github.com/BeNeNuTs/Kakuto/files/4623555/Player1Chronicle.txt)

**Comment by BeNeNuTs** [comment]
@Nikuichi @Jesaypa Need help on this one ^^ J'arrive pas à repro et je vois rien de déconnant dans les chronicles, les mouvements ont bien été unblocked à la fin du grab, et on détecte bien qu'on est repassé de takeOff à none et en stand à la fin du grab également.. du coup je vois pas :/

**Comment by Nikuichi** [comment]
CNR
