### ISSUE TITLE
j.HP hit might be inconsistent

### ISSUE THREAD

**Issue by Jesaypa** [BeNeNuTs/Kakuto#146]
Suivant la manière dont le coup start, puis la manière dont il est reçu, le follow des actions peut avoir des effets différents:

- Version normale:

![KAK_146_gNormal](https://user-images.githubusercontent.com/11633563/82575048-3c6f3500-9b88-11ea-8345-5af04d9da7e8.gif)

- Version "Push":

![KAK_146_gPush](https://user-images.githubusercontent.com/11633563/82575069-43964300-9b88-11ea-921a-a31fd1daf771.gif)

- Version "Bounce":

![KAK_146_gBounce](https://user-images.githubusercontent.com/11633563/82575089-4abd5100-9b88-11ea-9abc-5107735d1d93.gif)

**Tout dépend de l'angle du saut et du moment ou le coup est donné**.

**LOGS:**
[Player2Chronicle.txt](https://github.com/BeNeNuTs/Kakuto/files/4663250/Player2Chronicle.txt)
[Player1Chronicle.txt](https://github.com/BeNeNuTs/Kakuto/files/4663251/Player1Chronicle.txt)

**Comment by Jesaypa** [comment]
A savoir que je suis tombé là dessus en faisant des tests sur le time scale des coups. Mais je suis pas sûr que ça puisse avoir un rapport.

**Comment by BeNeNuTs** [comment]
Le fix de cette issue se trouve entre le setup de la friction (bug du push) et mon issue sur improve les jump collision (bug du bounce)

**Comment by Jesaypa** [comment]
Ok. J'avais aussi la version "Slide", pour un cross-up du swag:
![KAK_146_gSlide](https://user-images.githubusercontent.com/11633563/82576612-28c4ce00-9b8a-11ea-8c85-4b91d8f561d7.gif)

**Comment by Nikuichi** [comment]
C'est probablement pareil. A repro quand on a les fix des deux bugs mentionnés.
Je mets en need repro pour l'instant pour ne pas oublier.

**Comment by Nikuichi** [comment]
Note : repro avec le fix de #82

**Comment by BeNeNuTs** [comment]
Need repro sur celui là, histoire de tester un peu ce que j'ai mis en place et voir si on peut/veut faire mieux

**Comment by Nikuichi** [comment]
J'ai pas essayé avec le HP mais pour l'instant aucun souci avec le HK.

**Comment by Nikuichi** [comment]
C'est plus trop possible à faire j'ai bien l'impression.
