### ISSUE TITLE
Implement missing graph entries

### ISSUE THREAD

**Issue by Nikuichi** [BeNeNuTs/Kakuto#147]
On a discuté des anims restantes qui nécessitaient de modifier le graph / rajouter du code :

- stand to crouch
- crouch to stand
- teleport
- round won by KO or time over
- round lost time over 
- entry before round start
- suitcase hits adversary

Nice to have :
- turn around
- crouch turn around

**Comment by BeNeNuTs** [comment]
@Nikuichi Me faudrait les anims de StandToCrouch et CrouchToStand en ultra rough juste pour tester comment ça rend et si ça glisse pas pendant l'anim

**Comment by Nikuichi** [comment]
Amuse-toi.

**Comment by BeNeNuTs** [comment]
Note to self : Reste juste les turn around. à tester : Flip le perso + play de l'anim via trigger si on se trouve en stand ou crouch idle, sinon on bascule instant vers une attaque ou un walk/hit etc.
