### ISSUE TITLE
Frame drop and hit whiff may occurs when chaining strong hits on the corner.

### ISSUE THREAD

**Issue by Jesaypa** [BeNeNuTs/Kakuto#150]
![KAK_150_1_1g](https://user-images.githubusercontent.com/11633563/83947966-a4757a80-a81a-11ea-974d-26ac87448c7f.gif)

Logs extrait 1:
[Player1Chronicle.txt](https://github.com/BeNeNuTs/Kakuto/files/4740517/Player1Chronicle.txt)
[Player2Chronicle.txt](https://github.com/BeNeNuTs/Kakuto/files/4740518/Player2Chronicle.txt)

![KAK_150_2_1g](https://user-images.githubusercontent.com/11633563/83947971-ab03f200-a81a-11ea-982b-bb628d10a20f.gif)

Logs extrait 2:
[Player1Chronicle.txt](https://github.com/BeNeNuTs/Kakuto/files/4740500/Player1Chronicle.txt)
[Player2Chronicle.txt](https://github.com/BeNeNuTs/Kakuto/files/4740501/Player2Chronicle.txt)

- Je suis pas sûr de vraiment comprendre ce qui se passe. J'arrive pas à savoir si c'est à cause du debug, de la taille de la fenêtre, du fait que le P2 ne soit pas totalement on-screen, du shake cam ou du stop time...
- On voit juste qu'après le premier coup, plusieurs des suivants ont l'air de whiff complètement, provoqué ou pas par le frame drop. En tout cas on block, le pushback n'est pas appliqué pendant les hits chelous qui ne passent visiblement pas. Mais les dégâts semblent passer quand même sur les hits d'après?
- A savoir que ça n'arrive que dans le coin, et qu'avec des strong hits ou l'overhead
- Au final je sais meme pas si c'est un bug ou non, ou si ça vient de faire qu'on est capable de chain de strong hit alors que ça doit pas être possible
- Le truc qui m'a tilté ça vient surtout de faire que le pushback ne s'applique pas on block sur certains hits, le reste c'est le flou
- Help

**Comment by BeNeNuTs** [comment]
Beaucoup de frame drop lié au Chronicle qui log une tonne d'info. Faites une build et désactivez le development build pour retirer tout le debug et testez comme ça. Ou alors désactivez les Chronicle dans le chronicleConfig pour tester avec moins de drop

**Comment by Jesaypa** [comment]
07/06: Le frame drop est fixé, sur build et sur editeur.
Par contre le premier coup en guard whiff toujours après un hit dans le coin. Parfois le second aussi.

![KAK_150_2g](https://user-images.githubusercontent.com/11633563/83974603-e40d9680-a8ee-11ea-97c7-ea1e657d4778.gif)

LOGS:
[Player2Chronicle.txt](https://github.com/BeNeNuTs/Kakuto/files/4742499/Player2Chronicle.txt)
[Player1Chronicle.txt](https://github.com/BeNeNuTs/Kakuto/files/4742501/Player1Chronicle.txt)

- J'ai set un pushback attacker à 5 pour qu'on voit bien la différence quand ça touche et quand ça touche pas.
