### ISSUE TITLE
Hados go through the opponent after the hit.

### ISSUE THREAD

**Issue by Jesaypa** [BeNeNuTs/Kakuto#154]
![KAK_154_g2](https://user-images.githubusercontent.com/11633563/83968933-c7f8fd80-a8cc-11ea-9133-e8969951aef0.gif)
![KAK_154_g1](https://user-images.githubusercontent.com/11633563/83968931-c6c7d080-a8cc-11ea-92cb-6a0e35865f03.gif)

**LOGS:**
[Player2Chronicle.txt](https://github.com/BeNeNuTs/Kakuto/files/4742050/Player2Chronicle.txt)
[Player1Chronicle.txt](https://github.com/BeNeNuTs/Kakuto/files/4742051/Player1Chronicle.txt)

- Issue occurs on hit and on block

**Comment by BeNeNuTs** [comment]
C'est lié aux anims de destroy qui se jouent pas #153

**Comment by BeNeNuTs** [comment]
J'ai fixed #153, reste plus qu'à rajouter les bonnes anims
