### ISSUE TITLE
Try to shake opponent while hitstop

### ISSUE THREAD

**Issue by BeNeNuTs** [BeNeNuTs/Kakuto#155]

**Comment by Nikuichi** [comment]
On change ça en "essayer de shake le défenseur pendant le hitsop de l'attaquant ".

**Comment by BeNeNuTs** [comment]
@Nikuichi Tu pourrais me link la vidéo que tu avais capturé où on voyait bien le shake pendant le hitstop pour que je vois exactement à quoi ça ressemble ?

EDIT : En fait c'est bon je pense 🤓
