### ISSUE TITLE
Malik sometimes doesn't perform the fall animation when TP'ing to a air hado.

### ISSUE THREAD

**Issue by Nikuichi** [BeNeNuTs/Kakuto#157]
![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/12612621/84087087-ac374980-a9e9-11ea-80d8-c0cc011e2d01.gif)

[Player1Chronicle.txt](https://github.com/BeNeNuTs/Kakuto/files/4748937/Player1Chronicle.txt)
[Player2Chronicle.txt](https://github.com/BeNeNuTs/Kakuto/files/4748939/Player2Chronicle.txt)

**Comment by BeNeNuTs** [comment]
commit d9066fa7a1a2a18172b4e94b86bfe6ecf839d389 didn't fix the issue

**Comment by BeNeNuTs** [comment]
Fixed by commit 237dd95885407c45c7fc559859b1ac03a4f52c99
