### ISSUE TITLE
Successfully parrying a hit is required to activate the trigger

### ISSUE THREAD

**Issue by Nikuichi** [BeNeNuTs/Kakuto#161]
Chaque joueur commence le round avec zéro point de trigger.
Réussir à parry un coup donne un point de trigger.
On ne peut avoir qu'un point de trigger max.
Activer le trigger consomme un point de trigger.
Il faut aussi afficher le nombre de points disponibles à l'écran.

**Comment by Nikuichi** [comment]
Aussi un debug pour bypasser cette condition.

**Comment by Jesaypa** [comment]
Overall avoir la possibilité de gérer :

- le nombre de point de trigger total 

- le nombre de point de trigger acquis après un parry réussi

**Comment by BeNeNuTs** [comment]
@Nikuichi @Jesaypa Vous avez un exemple de à quoi ressemble l'affichage des points de trigger ? (Même si c'est du placeholder, que je sache la tête que ça a)
Est-ce qu'on a besoin de ça : 

> Overall avoir la possibilité de gérer 
> le nombre de point de trigger total
> le nombre de point de trigger acquis après un parry réussi

Sachant que @Nikuichi disait : 
> On ne peut avoir qu'un point de trigger max.

**Comment by Nikuichi** [comment]
Je reste sur l'idée qu'un point est suffisant.

Ca peut être juste une pastille on / off genre ça.
![image](https://user-images.githubusercontent.com/12612621/87369392-b0bec700-c580-11ea-8425-dcb49225574f.png)
