### ISSUE TITLE
Add a way to allow HitKO condition on multi-hits attacks

### ISSUE THREAD

**Issue by Jesaypa** [BeNeNuTs/Kakuto#168]
Lors d'une attaque multi-hits, need a moyen de pouvoir indiquer sur quel hit le HitKO condition s'applique.

**Comment by BeNeNuTs** [comment]
@Jesaypa  On veut pas tout le temps que ce soit sur le dernier hit ? Je pense que ce serait plus simple à implémenter. Du coup je pose la question au cas où pour éviter de faire un truc compliqué si on en a pas besoin ^^ et pour les autres hit, faudra qu'on puisse dire ce que c'est (aujourd'hui quand tu coches hitKO ça cache les autres champs mais là on va en avoir besoin)

**Comment by BeNeNuTs** [comment]
WNF
