### ISSUE TITLE
Hadoblast pushback is not applied anymore

### ISSUE THREAD

**Issue by Jesaypa** [BeNeNuTs/Kakuto#169]
![KAK_169_g](https://user-images.githubusercontent.com/11633563/85336266-a314a500-b4de-11ea-8a03-fe62a2832b18.gif)

**LOGS:**
[Player2Chronicle.txt](https://github.com/BeNeNuTs/Kakuto/files/4815608/Player2Chronicle.txt)
[Player1Chronicle.txt](https://github.com/BeNeNuTs/Kakuto/files/4815609/Player1Chronicle.txt)

**Comment by Nikuichi** [comment]
C'est parce que le nombre de hit max est à 4 et que l'adversaire n'en prend que 3. 
@Jesaypa Il faut que tu diminues le temps entre deux hits sur l'attaque.
