### ISSUE TITLE
Add conditional hits notifications

### ISSUE THREAD

**Issue by Nikuichi** [BeNeNuTs/Kakuto#174]
Détecter les sitiuations suivantes pour afficher une notification :
Côté défenseur :

- Coup overhead au sol encaissé
- Coup low encaissé
- Coup guard crush encaissé
- Coup crossup encaissé
- Counter

Côté attaquant (Nice to have) :

- Coup reversal lancé

(Coup spécial lancé dès la première trame après une relevée)

**Comment by BeNeNuTs** [comment]
@Nikuichi Un exemple d'affichage ? Comment on gère plusieurs notifs en même temps ?

**Comment by Nikuichi** [comment]
![image](https://user-images.githubusercontent.com/12612621/87368809-0abe8d00-c57f-11ea-8ccc-701e73dd4cf3.png)

Une notif est affichée pendant X secondes et disparait. Si on a besoin d'en afficher une nouvelle, on supprime l'ancienne qui n'avait pas encore disparu.
