### ISSUE TITLE
Hit air anim root motion resets vertical velocity

### ISSUE THREAD

**Issue by Nikuichi** [BeNeNuTs/Kakuto#176]
![ezgif com-video-to-gif (4)](https://user-images.githubusercontent.com/12612621/87244614-be6c3380-c43e-11ea-81de-015b6cb0df42.gif)

**Comment by BeNeNuTs** [comment]
Note to self, try to enable Kinematic instead of setting gravity scale to 0

**Comment by BeNeNuTs** [comment]
@Nikuichi Je te laisse faire papa :)
Je crois que j'avais fix le problème de gravité qui est cancel mais faut corriger la fin de l'animation hit_air qui blend vers celle de landing
