### ISSUE TITLE
Integrate UI elements

### ISSUE THREAD

**Issue by BeNeNuTs** [BeNeNuTs/Kakuto#184]

**Comment by Nikuichi** [comment]
- Pause menu
- Options panels
- Training options
- Replay
- Séprateur vertical

**Comment by Nikuichi** [comment]
UI pour savoir quel player met la pause (vu que si c'est le player 1 qui fait pause, on autorise que le player 1 à unpause

UI checkbox pour la training options (1 sprite pour le background, et 1 sprite pour la checkmark)

UI slider pour les options (pour pouvoir régler le son etc 1 sprite pour la barre du fond, 1 sprite pour la barre rempli (comme pour les jauges de vie, et un sprite pour le knob qui sert de marqueur du slider)

**Comment by Nikuichi** [comment]
Highlight sur l'option en cours d'édition.

**Comment by Nikuichi** [comment]
Flèches gauche droite.
