### ISSUE TITLE
Attacks stop dealing damage after dmage reduce cap

### ISSUE THREAD

**Issue by Nikuichi** [BeNeNuTs/Kakuto#187]
![ezgif com-video-to-gif (7)](https://user-images.githubusercontent.com/12612621/89050723-7a8c9000-d353-11ea-9dbc-024248558664.gif)

J'ai viré le hit pushback du LP pour tester.

![image](https://user-images.githubusercontent.com/12612621/89050815-9c861280-d353-11ea-867c-df5256032efc.png)

**Comment by BeNeNuTs** [comment]
On veut que ça cap à 1 minimum ?

**Comment by Nikuichi** [comment]
La courbe s'applatit à 0.2 donc ça devrait rester à 0.2 après 10 hits.
![image](https://user-images.githubusercontent.com/12612621/89058639-effe5d80-d35f-11ea-9799-4d048417d533.png)

**Comment by BeNeNuTs** [comment]
Oui sauf que les dégâts et les hp sont des entiers, donc 0.2 c'est pas possible :p cest d'ailleurs la raison pour laquelle il clamp à 0. Les dégâts peuvent donc pas être 0.2, c'est soit 0 (ce qu'on a là), soit 1 (le plus petit dégât possible en fait)
