### ISSUE TITLE
Cancel cannot be applied on whiff

### ISSUE THREAD

**Issue by Jesaypa** [BeNeNuTs/Kakuto#193]
VIDEO:
![KAK_193_1_g](https://user-images.githubusercontent.com/11633563/91229328-f2b75d00-e729-11ea-907b-5ed6f5e3087a.gif)

**LOGS:**
[Player1Chronicle.txt](https://github.com/BeNeNuTs/Kakuto/files/5126320/Player1Chronicle.txt)
[Player2Chronicle.txt](https://github.com/BeNeNuTs/Kakuto/files/5126321/Player2Chronicle.txt)

Si on décide de cancel un coup pendant un whiff, le cancel ne s'applique pas correctement (dans l'exemple, le cancel ne se joue qu'à la première trame disponible à la fin de l'animation du Hadoground).

Dans l'exemple: Hadoground cancel into > Trigger
- Le trigger ne possède pas de hit confirm
- Mais on souhaite quand même pouvoir cancel le hadoground à la première frame de dispo juste après l'envois du projectile:
![image](https://user-images.githubusercontent.com/11633563/91228385-6fe1d280-e728-11ea-96bb-e8b7b85ce1d5.png) 
![image](https://user-images.githubusercontent.com/11633563/91228408-7bcd9480-e728-11ea-8165-780cb55791b9.png)

Il nous faut une règle qui permet de pouvoir faire ça. Pour le moment le cancel ne s'applique que lorsqu'il y a hit confirm, comme ici:
![KAK_193_2_g](https://user-images.githubusercontent.com/11633563/91229447-25f9ec00-e72a-11ea-9b4b-c0a9d6959d1f.gif)

**Comment by BeNeNuTs** [comment]
De ce que tu me dis, pour l'instant tout fonctionne as designed. C'est à dire qu'une attaque ne peut être cancel qu'après un hit confirm. Si on veut une nouvelle règle pour le hadoground, il va falloir me dire laquelle.
@Jesaypa @Nikuichi Est ce que vous voulez que pour les attaques de type projectile on attend pas le hit confirm avant de pouvoir cancel ?

Ou alors vous voulez ce comportement eventuellement pour d'autres attaques que celles de types projectile et dans ce cas je rajoute une option dans l'anim event unblock attack pour vous permettre de dire si vous autoriser le cancel avant le hit confirm ou pas ?

(Désolé si je répète un peu ce que tu as dit, c'est juste pour être sûr d'avoir compris la demande)

**Comment by Nikuichi** [comment]
Si les deux solutions représentent la même charge de travail, j'opterais pour la deuxième vu qu'elle offre la possibilité de mettre ça où on veut si l'envie nous en prend.

Par contre, peu importe la solution privilégiée, on est d'accord qu'il s'agit d'autoriser en whiff spécifiquement le cancel du hado vers le trigger. 
Tu pourras cancel hado en hit puis super.
Tu pourras pas cancel hado en whiff puis super.
Tu pourras cancel hado en hit ou whiff vers trigger.

En écrivant ça de toute façon, je me dis que si tu autorises un truc à cancel le whiff, ça va couvrir le hit.

REF
https://youtu.be/itLCODuD-70?t=232

**Comment by BeNeNuTs** [comment]
Ouais ok donc c'est plus compliqué que prévu si ça concerne juste le trigger. Faut que je regarde
