### ISSUE TITLE
Fix anim events on anim last frame

### ISSUE THREAD

**Issue by Nikuichi** [BeNeNuTs/Kakuto#196]
![image](https://user-images.githubusercontent.com/12612621/91741831-90d97600-ebb5-11ea-8c1c-333d5a523115.png)
![unknown](https://user-images.githubusercontent.com/12612621/91741890-a6e73680-ebb5-11ea-8791-1831e248799e.png)

Présent sur le TP aussi. 
Faire la passe sur toutes les anims avec anim events.

**Comment by BeNeNuTs** [comment]
Petite précision, mais je pense que BlockAttack à la toute dernière trame (j'en ai vu quelques uns) ne sert pas à grand chose. Car soit ça va trigger un message d'erreur car on a déjà reçu le EndOfAnim à cette même trame, du coup y'a plus rien à bloquer vu qu'on est plus actuellement dans cette attaque. Soit on va réussir à bloquer les attaques mais dans la même trame on va les unblock puisqu'on passe dans le EndOfAnim. Bref, voiloù =)
