### ISSUE TITLE
[OPTIM] Investigate performance issues

### ISSUE THREAD

**Issue by BeNeNuTs** [BeNeNuTs/Kakuto#199]

**Comment by BeNeNuTs** [comment]
After a few tests, performance hits seems to be related to GPU. Rendering the meshes and lighting can cause low FPS on 1v1 map.
Gfx.WaitForPresent seems to take sometimes > 25ms, so fps can drop below 30.
Need to check if this is related to VSync, Targetframerate, polycount or runtime lighting.

**Comment by BeNeNuTs** [comment]
@CaptainNecate KDO :)
Merci 👍

**Comment by Nikuichi** [comment]
Remplacer mesh low poly
