### ISSUE TITLE
Any hit canceled into HadoBlast do not hit the opponent.

### ISSUE THREAD

**Issue by Jesaypa** [BeNeNuTs/Kakuto#200]
![KAK_200_g](https://user-images.githubusercontent.com/11633563/92328057-7e03ed00-f05e-11ea-970e-8ee6d910bf3a.gif)

![image](https://user-images.githubusercontent.com/11633563/92328082-b0154f00-f05e-11ea-9705-2a7d36b19004.png)

LOGS:
[Player2Chronicle.txt](https://github.com/BeNeNuTs/Kakuto/files/5179806/Player2Chronicle.txt)
[Player1Chronicle.txt](https://github.com/BeNeNuTs/Kakuto/files/5179807/Player1Chronicle.txt)

**Comment by Jesaypa** [comment]
J'ai éssayé avec des lights (sLP, sHK, sHP) et avec un special (Hadoground, exemple au dessus) et ça ne touche jamais l'opponnent dans chaque scénario. J'ai tenté en grossissant la Hitboxe du blast, mais comme le souligne le screen le coup reach correctement mais rien ne se passe.

**Comment by BeNeNuTs** [comment]
C'est uniquement la hadoblast ou si tu cancel avec n'importe quelle autre attack ça marche pas non plus ?

**Comment by Jesaypa** [comment]
Jusqu'à maintenant je n'ai vu cet effet qu'avec le Hadoblast. Présentement on a des cancel de normaux into Hadoground par exemple, et y'a pas de soucis. D’où mon interrogation.
