### ISSUE TITLE
Cancels can only be performed very early in the cancellable animation

### ISSUE THREAD

**Issue by Nikuichi** [BeNeNuTs/Kakuto#202]
sHK --> Blast est un cancel possible mais on ne peut cancel le sHK que très tôt dans son anim  alors que la fenêtre de cancel ressemble à ça.

![image](https://user-images.githubusercontent.com/12612621/94041051-0659f000-fdca-11ea-8f22-14d8725583d9.png)

On peut cancel jusqu'à cette trame. 
![image](https://user-images.githubusercontent.com/12612621/94041125-1b368380-fdca-11ea-997a-920fc7c4802e.png)

[Player1Chronicle.txt](https://github.com/BeNeNuTs/Kakuto/files/5269598/Player1Chronicle.txt)
[Player2Chronicle.txt](https://github.com/BeNeNuTs/Kakuto/files/5269599/Player2Chronicle.txt)

**Comment by BeNeNuTs** [comment]
Avec les logs actuels je vois malheureusement rien d'intéressant :/
A minima il faudrait faire une repro en aillant coché le log des inputs pour que je puisse voir sur quoi tu appuies et de quand à quand les inputs sont valides : 
![image](https://user-images.githubusercontent.com/2429048/95021503-9d983080-0671-11eb-8eab-bdf3c3a932f2.png)
Et une vidéo montrant l'action histoire de mieux cerner à quel moment ça déconne.

J'ai essayé de faire le test de mon côté et tout fonctionne bien à priori (j'ai juste modifié les inputs de hadoblast pour que ce soit plus simple à lancer), et dès que je hit, si j'appuie sur l'input d'hadoblast ça cancel bien sHK par hadoblast. à voir si le fait que tu arrives pas à le lancer viendrait pas du setup des durées de vie des inputs.

**Comment by BeNeNuTs** [comment]
Vient certainement du TimeScale
![image](https://user-images.githubusercontent.com/2429048/95794831-20139680-0ce9-11eb-9bd0-05e6e913cc46.png)
