### ISSUE TITLE
Separate trigger palettes for both players

### ISSUE THREAD

**Issue by Nikuichi** [BeNeNuTs/Kakuto#204]
Pendant que le trigger est actif, il faut une palette différente par joueur.
![image](https://user-images.githubusercontent.com/12612621/96350925-8c5f1300-10b8-11eb-97c7-0c30def53842.png)

**Comment by BeNeNuTs** [comment]
![image](https://user-images.githubusercontent.com/2429048/96373227-5c247c80-116b-11eb-9e27-8cba8518bec8.png)
