### ISSUE TITLE
EX blast inputs can't be performed

### ISSUE THREAD

**Issue by Nikuichi** [BeNeNuTs/Kakuto#207]
Le EX hado QCF 2P fonctionne parfaitement alors que le EX blast QCB 2P ne fonctionne pas.
Discord

[Player2Chronicle.txt](https://github.com/BeNeNuTs/Kakuto/files/5411173/Player2Chronicle.txt)
[Player1Chronicle.txt](https://github.com/BeNeNuTs/Kakuto/files/5411174/Player1Chronicle.txt)

**Comment by Nikuichi** [comment]
![image](https://user-images.githubusercontent.com/12612621/96636461-9cc3f780-131d-11eb-9991-051544940f62.png)
![image](https://user-images.githubusercontent.com/12612621/96636483-a188ab80-131d-11eb-934b-eb535974763d.png)

**Comment by BeNeNuTs** [comment]
T'as mis standLP + standHP 2 fois
