### ISSUE TITLE
Multihit parry : <

### ISSUE THREAD

**Issue by Nikuichi** [BeNeNuTs/Kakuto#208]
SA MARSH PA : <
[Player1Chronicle.txt](https://github.com/BeNeNuTs/Kakuto/files/5447512/Player1Chronicle.txt)
[Player2Chronicle.txt](https://github.com/BeNeNuTs/Kakuto/files/5447513/Player2Chronicle.txt)

![image](https://user-images.githubusercontent.com/12612621/97349506-d9e53800-188f-11eb-9368-61b22682f3e7.png)
![image](https://user-images.githubusercontent.com/12612621/97349597-f2ede900-188f-11eb-8aae-e20cd76b7e4e.png)

Video Discord

**Comment by BeNeNuTs** [comment]
https://discordapp.com/channels/601492307707166732/758364518862290965/770725574196199435

**Comment by BeNeNuTs** [comment]
Fixed e66a13e3
