### ISSUE TITLE
Parry can be cancelled with itself

### ISSUE THREAD

**Issue by Nikuichi** [BeNeNuTs/Kakuto#209]
Tous les parry whiff après un premier parry succes peuvent être cancel par eux-mêmes.
Video Discord
P2 spamme le parry.

Probablement lié à #208 

[Player2Chronicle.txt](https://github.com/BeNeNuTs/Kakuto/files/5447708/Player2Chronicle.txt)
[Player1Chronicle.txt](https://github.com/BeNeNuTs/Kakuto/files/5447709/Player1Chronicle.txt)

**Comment by BeNeNuTs** [comment]
https://discordapp.com/channels/601492307707166732/758364518862290965/770733743383904266

**Comment by BeNeNuTs** [comment]
Should be fixed e66a13e3
