### ISSUE TITLE
Spam crouch hits really quickly make the character stands up

### ISSUE THREAD

**Issue by Jesaypa** [BeNeNuTs/Kakuto#211]
If the player is spamming any crouch hit really quickly, which means without waiting the beginning of the recovery animation, the character may rise him from himself even if the player is still pressing down the stick.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/11633563/100390018-586bfb80-302f-11eb-91d5-de15309ff673.gif)
1) Example of spamming while crouched (look at the input execution speed)

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/11633563/100390046-6b7ecb80-302f-11eb-8615-b8c0b1f2f14c.gif)
2) Example of trying to follow a correct rythm of input execution

LOGS:
[Player1Chronicle.txt](https://github.com/BeNeNuTs/Kakuto/files/5604900/Player1Chronicle.txt)
[Player2Chronicle.txt](https://github.com/BeNeNuTs/Kakuto/files/5604901/Player2Chronicle.txt)

**Comment by BeNeNuTs** [comment]
Hm, je vois d'où ça vient, je l'ai pété en réparant le fait qu'on pouvait crouch indéfiniment à la fin du round et du coup bloquer l'anim de fin
