### ISSUE TITLE
Projectile can go too high after performing a Hadoair

### ISSUE THREAD

**Issue by Jesaypa** [BeNeNuTs/Kakuto#213]
The player can perform a TP on an Hadoair way too high. It seems that the projectile is not destroyed soon enough when getting out of vision from the main camera.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/11633563/101292489-05086300-3810-11eb-9aa6-a061cdfdb702.gif)

**Comment by BeNeNuTs** [comment]
![image](https://user-images.githubusercontent.com/2429048/102008331-e20a1180-3d2f-11eb-9103-3440fa839aa9.png)
