### ISSUE TITLE
Make remap inputs menu

### ISSUE THREAD

**Issue by BeNeNuTs** [BeNeNuTs/Kakuto#219]

**Comment by Nikuichi** [comment]
![image](https://user-images.githubusercontent.com/12612621/104080159-b858e300-5226-11eb-8bb1-c1b2cb75c9d0.png)

**Comment by Nikuichi** [comment]
![image](https://user-images.githubusercontent.com/12612621/104080169-c575d200-5226-11eb-8ab2-792598d9d27f.png)

**Comment by BeNeNuTs** [comment]
- Affichage input PS4 ou X1 en fonction de la manette du player.
- Vérification pour ne jamais avoir d'input vide ni même un input assigné à 2 coups.
- Push A puis affichage waiting for input..
