### ISSUE TITLE
Add feedback when P1 tries to change P2 input and vice versa

### ISSUE THREAD

**Issue by BeNeNuTs** [BeNeNuTs/Kakuto#238]
@Nikuichi On met quel feedback ?

**Comment by BeNeNuTs** [comment]
On fait clignoter d'une couleur le highlight

**Comment by BeNeNuTs** [comment]
Tu me diras si ça te convient le feedback de clignotement du highlight (j'ai pas exposé la couleur de clignotement mais je peux si y'a besoin)
Je te laisserai régler la durée du feedback ainsi que la speed du clignotement ici : 
![image](https://user-images.githubusercontent.com/2429048/108436583-f1379f00-724b-11eb-95cd-51a1371944c3.png)

**Comment by Nikuichi** [comment]
Pas besoin de changer les data, t'es GD.
