### ISSUE TITLE
Implement launch and hit juggles

### ISSUE THREAD

**Issue by Nikuichi** [BeNeNuTs/Kakuto#243]
Certains coups te mettent en état de juggle, et certains coups touchent une fois que tu es en état de juggle.

En gros oui il faut deux flag.
juggle_entry et juggle_exit

![image](https://user-images.githubusercontent.com/12612621/107685221-0a68aa80-6ca4-11eb-92aa-e19d38b0b347.png)

**Comment by BeNeNuTs** [comment]
à régler pour tous le coups : 
![image](https://user-images.githubusercontent.com/2429048/108632600-245a7800-7470-11eb-9cfe-5f636790a649.png)
