### ISSUE TITLE
Allow proximity boxes on projectiles

### ISSUE THREAD

**Issue by Nikuichi** [BeNeNuTs/Kakuto#245]
![image](https://user-images.githubusercontent.com/12612621/108243128-062e0880-714e-11eb-93ad-13e058f2e285.png)

**Comment by BeNeNuTs** [comment]
@Nikuichi On prend les nouvelles habitudes :)
Faut setup les hitbox/proximitybox sur les projectiles suitcase.prefab et hadoinferno_projectile.prefab. Pas besoin de modifier les anims, tu peux directement tweak la size de chacun des colliders et les laisser actif par défaut vu qu'ils vont pas changer au cours de l'animation (peut être à la limite les désactiver pendant l'anim d'open pour éviter de prendre un damage quand un player se TP dessus)
