### ISSUE TITLE
Sound implementation

### ISSUE THREAD

**Issue by Nikuichi** [BeNeNuTs/Kakuto#250]
Tous les triggers nécessaires sont listés ici : 
https://docs.google.com/spreadsheets/d/1Uko02tCJpQhrw7PO1-gtywhRR4WNCB9C/edit#gid=1235399558

Les spécificités des triggers de coup sont précisées ici : 
https://docs.google.com/document/d/1H10QftBdKZLwO_zEkFUJzifObqk8quHQa12sZsMTH0U/edit#heading=h.botik3o0xc7y

**Comment by BeNeNuTs** [comment]
C'est cool pour les docs ! 
Il me faudrait aussi savoir si on veut duck la musique pendant un menu pause et pendant qu'on joue une voix (genre annonce de round). Et si on veut blend les musiques quand on passe d'une scène à l'autre. Et puis on verra pour la suite, la UI etc
