### ISSUE TITLE
Refill player HP after a tweakable delay post hitstun / blockstun

### ISSUE THREAD

**Issue by Nikuichi** [BeNeNuTs/Kakuto#268]
**Training map only**
Quand un player se fait toucher en hit ou en block, on attend un délai settable en data avant de remplir sa barre de vie.
Points bonus si on remplit la barre progressivement (mais rapidement) plutôt qu'instant.

**Comment by BeNeNuTs** [comment]
@Nikuichi Pour le setup
![image](https://user-images.githubusercontent.com/2429048/132141074-b6b9e7ab-1c19-4d43-90f2-48c4dae96e6b.png)

Les barres se remplissent à la même vitesse qu'elles se vident déjà actuellement avec ce param : 
![image](https://user-images.githubusercontent.com/2429048/132141100-5eb151f8-b05e-4875-9f17-b9849192ed49.png)
