### ISSUE TITLE
Display combo damage

### ISSUE THREAD

**Issue by Nikuichi** [BeNeNuTs/Kakuto#269]
**Training map only**

Après chaque coup en hit ou garde, on affiche les dégâts totaux du combo en prenant le scalling en compte.

Exemples :
https://lowkey.gg/v/50613ee4-d49a-4083-8fd9-7d22676accad?cf=uploadMsg
https://lowkey.gg/v/12d50fb1-2755-4234-8bb0-2632ef309876?cf=uploadMsg

Il faut regarder uniquement la ligne 'combo damage' dans les deux exemples.

**Comment by BeNeNuTs** [comment]
@Nikuichi J'ai terminé celui là mais j'aurai qlq questions avant de close la tâche.

1. Faudra qu'on discute viteuf de l'emplacement de la UI. 
Pour l'instant je l'ai mis pour les 2 joueurs (ce sera paramétrable comme le reste via PlayerSettings pour savoir si on l'affiche sur P1 et/ou P2 dans telle ou telle scène (comme ça au moins on fait comme on veut)
Pour l'instant je l'ai mis ici : 
![image](https://user-images.githubusercontent.com/2429048/132141855-450df7c7-2667-4892-86b4-f0ad45151d22.png)

2. Est-ce que ça reste affiché tout le temps comme sur tes vidéos ou bien ça disparait comme le fait actuellement notre compteur de hits ? (pour l'instant je l'ai codé comme ça, ça apparait/disparait avec le compteur de hits)
