### ISSUE TITLE
Players aren't properly aligned when a throw is performed in the corner

### ISSUE THREAD

**Issue by Nikuichi** [BeNeNuTs/Kakuto#53]
When throwing in the corner, one of the players might not be snapped to position to prevent OOB.

![corner_throw](https://user-images.githubusercontent.com/12612621/65999384-94441900-e49d-11e9-9db7-a80d79b7df44.gif)

In that case we should snap the player away from the corner.

**Comment by Nikuichi** [comment]
Or maybe it has to do with players able to basically walk through each other. ¯\_(ツ)_/¯

**Comment by Jesaypa** [comment]
Issue still occurs - _12/01/19_
