### ISSUE TITLE
Better diagonal directions registering

### ISSUE THREAD

**Issue by DocUnco** [BeNeNuTs/Kakuto#58]
Il faut trop de précision pour les quatre diagonales.

**Comment by Jesaypa** [comment]
Issue still occurs - _12/01/19_

**Comment by BeNeNuTs** [comment]
@Nikuichi @Jesaypa  Can be achieved by tweaking dead zone of inputs Vertical
This needs to be done for all Vertical input settings (each Vertical setting is for gamepad from 1 to 8) 
![image](https://user-images.githubusercontent.com/2429048/81738018-482c6e80-9499-11ea-8ccf-45264d856a42.png)

But to know which one is linked to your character you can check Gamepad index debug display (in my case Vertical2, this means that the gamepad has been detected in index 2) : 
![image](https://user-images.githubusercontent.com/2429048/81738125-7b6efd80-9499-11ea-85d3-41c0aca37c3b.png)

If you need to test it on 1v1 map, you can display this gamepad debug by enable it in ScenesConfig : 
![image](https://user-images.githubusercontent.com/2429048/81738237-ace7c900-9499-11ea-8ddd-a7677f6ab8cf.png)

For example, I could improve the diagonal registering by decrease dead zone of Vertical input setting from 0.47 to 0.3. But I let you see by yourself what do you prefer :)

**Comment by Jesaypa** [comment]
De part le push juste au dessus et de ce qu'on a discuté avec David:
-La dead zone est maintenant plus permissive et permet de launch le jump diagonal plus aisément

Ce qu'il y a encore à faire:
-Pour l'instant, la pression progressive du stick a été baissée, donc le joueur peut lancer le saut diagonal en pressant progressivement moins longtemps le saut
MAIS
-Si le joueur effectue un "tap" sur le stick, le saut restera sur place et la diagonale ne sera pas prise en compte, donc logiquement faudrait aller voir en code si on peut pas rendre le tout plus léger et modifier la manière dont en prend en compte l'input. @BeNeNuTs 

**!!Faire gaffe à ne pas créer des régressions sur les autres input hors directionnels!!**
