### ISSUE TITLE
Record input delay SF4

### ISSUE THREAD

**Issue by BeNeNuTs** [BeNeNuTs/Kakuto#65]
Essayer de voir comment fonctionne l'input delay sur SF4. Faut voir ce qu'il se passe quand tu lances un coup avec 1 input et quand tu lances un coup avec plusieurs inputs en essayant de faire frame perfect et avec du délais entre les inputs (genre pour un coup avec 2 inputs) et voir frame par frame ce qu'il se passe. Après si les inputs s'affichent une fois qu'ils sont validés (et pas au moment de l'input manette) tu verras pas grand chose. Bien que tu verras peut être les inputs du coup avec plusieurs inputs s'afficher en une seule fois alors que t'avais appuyé sur un puis sur l'autre. Voir si les inputs arrivent au moment où tu fais l'input manette ou bien quelques frames plus tard.

**Comment by Nikuichi** [comment]
https://we.tl/t-2uGnhsL8Oh
