### ISSUE TITLE
Block pushback stutters when hitting a crouching opponent with strong normals

### ISSUE THREAD

**Issue by Nikuichi** [BeNeNuTs/Kakuto#76]
Strong normals

![ezgif com-video-to-gif (6)](https://user-images.githubusercontent.com/12612621/67473218-96d7ff80-f652-11e9-9049-3e1b22241ea1.gif)

Light normals

![ezgif com-video-to-gif (7)](https://user-images.githubusercontent.com/12612621/67473379-d7d01400-f652-11e9-93ba-3b0fb9c144d2.gif)

**Comment by Nikuichi** [comment]
Works the same when attacker uses standing or crouching normals.

**Comment by BeNeNuTs** [comment]
Due to slow mo on strong hit I think
