### ISSUE TITLE
Hit counter displays 2 hits when hitting a ground followed by jump attack

### ISSUE THREAD

**Issue by Nikuichi** [BeNeNuTs/Kakuto#79]
- Hit ground normal
- Wait for dummy end of blockstun
- jHP

![2hitcombo](https://user-images.githubusercontent.com/12612621/67535471-0d1c4680-f6d3-11e9-99e4-a09cd2704fd8.gif)

**Comment by Jesaypa** [comment]
Issue still occurs - _12/01/19_

**Comment by BeNeNuTs** [comment]
Certainement lié à l'auto block

**Comment by Jesaypa** [comment]
**_CNR 18/04_**
