### ISSUE TITLE
Combos are inconsistent

### ISSUE THREAD

**Issue by Nikuichi** [BeNeNuTs/Kakuto#80]
Combo done in with a macro offers inconsistent results.
LP > LP hits for 2 hits sometimes, dummy is able to block second hit other times.

![macro_lp](https://user-images.githubusercontent.com/12612621/67535986-4ce42d80-f6d5-11e9-8ec8-9a5a830ef7fe.gif)

Macro used
![2019-10-25_03h00_06](https://user-images.githubusercontent.com/12612621/67535782-705aa880-f6d4-11e9-8570-26489a7af296.png)

Two LP with approx 22f in-between which should always combo according to frame data.

![2019-10-25_03h03_31](https://user-images.githubusercontent.com/12612621/67535873-ed861d80-f6d4-11e9-8324-f39997c93074.png)

Macro in 1v1 map

![macro_lp2](https://user-images.githubusercontent.com/12612621/67552317-1de8ae80-f70b-11e9-8d7a-fbda0dbb9825.gif)

**Comment by Nikuichi** [comment]
Repro avec video et logs.
Toujours avec exactement la même macro. Une fois que le bug est trigger, il faut que j'attende très longtemps après la fin du hitstun du dummy pour que la macro fasse combo.

**Comment by Nikuichi** [comment]
![repro#80](https://user-images.githubusercontent.com/12612621/80309077-dbe01880-87d2-11ea-8707-acd8231716e7.gif)

**Comment by Nikuichi** [comment]
[Player2Chronicle#80.txt](https://github.com/BeNeNuTs/Kakuto/files/4535394/Player2Chronicle.80.txt)
[Player1Chronicle#80.txt](https://github.com/BeNeNuTs/Kakuto/files/4535395/Player1Chronicle.80.txt)

**Comment by BeNeNuTs** [comment]
Need to remove ClearTriggeredInputs on BlockAttacks and check that inputpersistency/delay etc are frame reliable. Add chronicle info on inputs + config to know which category to log.
