### ISSUE TITLE
Malik is already airborne during jump takeoff and dips under the ground during landing

### ISSUE THREAD

**Issue by Nikuichi** [BeNeNuTs/Kakuto#81]
![jump_anim](https://user-images.githubusercontent.com/12612621/67551246-be899f00-f708-11e9-98bf-3a23b14fa97f.gif)

Takeoff

![image](https://user-images.githubusercontent.com/12612621/67551470-4bccf380-f709-11e9-9513-f4560b5af61a.png)

Landing

![image](https://user-images.githubusercontent.com/12612621/67551461-466fa900-f709-11e9-8933-2e588d893009.png)

**Comment by Nikuichi** [comment]
Actual movement should probably only be applied during jump anim and not jumptakeoff or jumplanding.

**Comment by BeNeNuTs** [comment]
dips under the ground during landing is FIXED
