### ISSUE TITLE
Improve jump collisions when player lands on top of opponent

### ISSUE THREAD

**Issue by Nikuichi** [BeNeNuTs/Kakuto#82]
![jump_coll](https://user-images.githubusercontent.com/12612621/67553800-4a51fa00-f70e-11e9-90e0-d478667fa6e0.gif)

**Comment by Nikuichi** [comment]
Quand P1 saute et atterrit sur P2.
Au milieu de l'écran, ça pousse P2.
Ca, on est à peu près bon.
Dans le coin, c'est un peu particulier.
En mettant que P2 soit dans le coin droit, soit P1 atterrit sur la droite de P2, dans le coin et là on pousse P2 pareil qu'au milieu de l'écran.
Soit P1 atterrit sur la gauche de P2 et c'est P1 qu'on décale.

![jump_ontop](https://user-images.githubusercontent.com/12612621/67602250-8456e680-f776-11e9-8bda-2c299142e8a2.gif)

![image](https://user-images.githubusercontent.com/12612621/67602265-8c168b00-f776-11e9-8ef0-69953502e284.png)

**Comment by Jesaypa** [comment]
Issue still occurs - _12/01/19_
